### Docker Compose example
networks:
  my_network:
    name: my_network
    driver: bridge

services:
  ct_adminer:
    image: ghcr.io/agorastismesaio/docker-img-adminer:main
    hostname: adminer
    container_name: ct_adminer
    restart: always
    ports:
      - 8080:8080 # Management console port
    environment:
        ADMINER_DB: guacamole_db
        ADMINER_DRIVER: pgsql
        ADMINER_PASSWORD: password
        ADMINER_SERVER: postgres
        ADMINER_USERNAME: guacamole
        ADMINER_AUTOLOGIN: 1
        ADMINER_NAME: SW Guacamole DB
    networks:
      - my_network
